//
// Generated file, do not edit! Created by nedtool 5.3 from nodes/messages/PositionUpdate.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __POSITIONUPDATE_M_H
#define __POSITIONUPDATE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>nodes/messages/PositionUpdate.msg:17</tt> by nedtool.
 * <pre>
 * message PositionUpdate
 * {
 * }
 * </pre>
 */
class PositionUpdate : public ::omnetpp::cMessage
{
  protected:

  private:
    void copy(const PositionUpdate& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PositionUpdate&);

  public:
    PositionUpdate(const char *name=nullptr, short kind=0);
    PositionUpdate(const PositionUpdate& other);
    virtual ~PositionUpdate();
    PositionUpdate& operator=(const PositionUpdate& other);
    virtual PositionUpdate *dup() const override {return new PositionUpdate(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PositionUpdate& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PositionUpdate& obj) {obj.parsimUnpack(b);}


#endif // ifndef __POSITIONUPDATE_M_H

